insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Ácido, Essência', 1,  'Unidade', 0.2, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Açúcar Cristal', 1000,  'Grama', 3.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Açúcar Mascavo', 1000,  'Grama', 14.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Açúcar Refinado - União', 1000,  'Grama', 5.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Ameixa', 1000,  'Grama', 28.59, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Amendoim', 1000,  'Grama', 17.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Arame para Flores', 50,  'Unidade', 9.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Hamburguer P', 100,  'Unidade', 20.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Hamburguer G', 100,  'Unidade', 27.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Pink Blue 3 Trufas', 1,  'Unidade', 1.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Pink Blue 16/6', 1,  'Unidade', 3.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Pink Blue 5/6', 1,  'Unidade', 1.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Pink Blue 20/17', 1,  'Unidade', 4.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Pink Blue 50g', 1,  'Unidade', 1.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Transporte', 1,  'Unidade', 4.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Caixa Tubo', 1,  'Unidade', 2.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 15 cm', 1,  'Unidade', 1.4, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 20 cm', 1,  'Unidade', 2.2, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 25 cm', 1,  'Unidade', 2.9, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 30 cm', 1,  'Unidade', 3.8, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 35 cm', 1,  'Unidade', 4.9, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 40 cm', 1,  'Unidade', 5.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cake Borde 45 cm', 1,  'Unidade', 6.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Cartão 6cm', 100,  'Unidade', 30.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Casquinha de Sorvete', 50,  'Unidade', 12.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Castanha Inteira', 1000,  'Grama', 62.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Castanha Quebrada', 1000,  'Grama', 48.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chantilly Amelia Supreme', 1000,  'Mililitro', 14.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate Confeiteiro - Harold', 1000,  'Grama', 17.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate Chepes', 1000,  'Grama', 16.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate em Barra Nobre - Melken', 1000,  'Grama', 30.7, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate em Barra - Top', 1000,  'Grama', 25.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate em Pó - Melken', 1000,  'Grama', 30.65, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Chocolate em Pó - Namur', 1000,  'Grama', 26.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Copo Bolha', 1,  'Unidade', 0.9, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Corante em Pó', 1,  'Unidade', 10.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Creme de Leite - Italac', 200,  'Grama', 2.47, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Damasco', 1000,  'Grama', 53.3, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Doce de Leite', 395,  'Grama', 4.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Embalagem Bandeja Plast Brigadeiro', 1,  'Unidade', 0.21, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Embalagem Bolo Piscina', 100,  'Unidade', 74.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Embalagem Sachê', 1,  'Unidade', 2.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Embalagem Super Fatia', 10,  'Unidade', 12.25, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Embalagem Telinha', 100,  'Unidade', 5.55, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Emulsificante', 200,  'Grama', 6.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Farinha de Trigo - Primor', 1000,  'Grama', 3.9, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fermento', 100,  'Grama', 3.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fermento Biológico', 20,  'Grama', 2.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita de Cetim Enne N° 1', 10,  'Metro', 27.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita de Cetim Enne N° 2', 10,  'Metro', 32.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita de Cetim Enne N° 3', 10,  'Metro', 37.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita de Cetim Nº 2', 10,  'Metro', 2.15, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita de Cetim Nº 3', 10,  'Metro', 4.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Fita Floral', 10,  'Metro', 6.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Frutas Cristalizadas', 1000,  'Grama', 8.19, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Granulado Granulé ao Leite - Melken', 400,  'Grama', 28.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 10 cm / 15 cm', 1,  'Unidade', 4.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 15 cm / 15 cm', 1,  'Unidade', 6.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 20 cm / 15 cm', 1,  'Unidade', 10.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 25 cm / 15 cm', 1,  'Unidade', 12.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 30 cm / 15 cm', 1,  'Unidade', 18.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 35 cm / 15 cm', 1,  'Unidade', 20.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Isopor 40 cm / 15 cm', 1,  'Unidade', 22.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Leite em Pó', 1000,  'Grama', 5.8, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Leite Condensado - Italac', 395,  'Grama', 3.9, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Leite de Coco - Sococo', 200,  'Mililitro', 5.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Guardanapo', 1.600,  'Unidade', 20.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Maizena', 200,  'Grama', 3.89, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Margarina', 1000,  'Grama', 6.7, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Merengue Powder Arcolor', 150,  'Grama', 9.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Morango', 60,  'Unidade', 15.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Nozes', 1000,  'Grama', 112.34, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Nutella Ferreiro', 650,  'Grama', 25.39, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Ovos', 12,  'Dúzia', 4.2, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Papel Crepom - Italiano', 1,  'Unidade', 10.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Papel Filme', 100,  'Metros', 0.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Papel para Bombom', 100,  'Unidade', 8.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Papel Seda', 1,  'Unidade', 0.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Papel Toalha', 750,  'Unidade', 8.29, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Passas', 1000,  'Grama', 25.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Pasta Americana', 800,  'Grama', 20.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Pasta de Flores', 500,  'Grama', 16.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Plástico Bolha', 50,  'Unidade', 0.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Pó Mavalério', 100,  'Grama', 7.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sachê de Alfajor', 1,  'Unidade', 9.85, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Saco Celofane M', 1,  'Unidade', 1.4, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Papel G', 1,  'Unidade', 2.35, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Papel M', 1,  'Unidade', 1.8, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Papel P', 1,  'Unidade', 1.5, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Papel PP', 1,  'Unidade', 1.2, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Boca de Palhaço', 100,  'Unidade', 44.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sacola Delivery', 10,  'Unidade', 10.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Sal', 1000,  'Grama', 2.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Suco de Uva Aurora 500 ml', 1,  'Unidade', 9.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Suculenta', 15,  'Unidade', 100.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Taça de Acrílico 1.5 ml', 1,  'Unidade', 11.00, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Tâmara sem caroço', 1000,  'Grama', 55.61, now());
insert into public.insumo (dsInsumo, nrQtdBase, dsMedida, vlPreco, dtCadastro) values ('Tira de Acetato Bwb 10cm', 4,  'Metros', 7.00, now());
